### ISSUE TITLE
## Issue: No response when sending messages

### ISSUE THREAD

**Issue by sol1560** [langmanus/langmanus#47]
### Description
When sending messages in the chat interface, there is no response from the system.

### Steps to Reproduce
1. Open the chat interface
2. Type a message and send
3. No response is received

### Expected Behavior
The system should respond to user messages.

### Current Behavior
Messages are sent but no responses are received.

**Comment by hetaoBackend** [comment]
Could u plz elaborate a bit more about the error message on Frontend or Backend? Thanks!

**Comment by wzhudev** [comment]
Same here. I configured and the response is empty.

```yaml
# if true, use conf.yaml, else use original .env config, default false
USE_CONF: true

# LLM Config
## follow litellm config: https://docs.litellm.ai/docs/providers
REASONING_MODEL:
  model: "openrouter/deepseek/DeepSeek-R1"
  api_key: "sk-or-v1-1d8c0240be6219792438b4cfe510756387c0"
  api_base: "https://openrouter.ai"

BASIC_MODEL:
  model: "openrouter/openai/gpt-4o-2024-08-06"
  api_base:  "https://openrouter.ai" 
  api_key: "sk-or-v1-1d8c0240be6219792438b4cfe510756387c0"

VISION_MODEL:
  model: "openrouter/openai/gpt-4o-2024-08-06"
  api_base: "https://openrouter.ai"
  api_key: "sk-or-v1-1d8c0240be6219792438b4cfe510756387c0"
```
